<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions xmlns:tns="http://localhost:7001" xmlns:wsr="http://www.openuri.org/2002/10/soap/reliability/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" xmlns:conv="http://www.openuri.org/2002/04/wsdl/conversation/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://localhost:7001">
 <message name="add">
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="intVal">
  </part>
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="intVal0">
  </part>
 </message>
 <message name="addResponse">
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="result">
  </part>
 </message>
 <message name="subtract">
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="intVal">
  </part>
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="intVal0">
  </part>
 </message>
 <message name="subtractResponse">
  <part xmlns:partns="http://www.w3.org/2001/XMLSchema" type="partns:int" name="result">
  </part>
 </message>
 <portType name="AdderPort">
  <operation name="add">
   <input message="tns:add">
   </input>
   <output message="tns:addResponse">
   </output>
  </operation>
  <operation name="subtract">
   <input message="tns:subtract">
   </input>
   <output message="tns:subtractResponse">
   </output>
  </operation>
 </portType>
 <binding type="tns:AdderPort" name="AdderPort">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http">
  </soap:binding>
  <operation name="add">
   <soap:operation style="rpc" soapAction="">
   </soap:operation>
   <input>
    <soap:body namespace="http://localhost:7001" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded">
    </soap:body>
   </input>
   <output>
    <soap:body namespace="http://localhost:7001" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded">
    </soap:body>
   </output>
  </operation>
  <operation name="subtract">
   <soap:operation style="rpc" soapAction="">
   </soap:operation>
   <input>
    <soap:body namespace="http://localhost:7001" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded">
    </soap:body>
   </input>
   <output>
    <soap:body namespace="http://localhost:7001" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded">
    </soap:body>
   </output>
  </operation>
 </binding>
 <service name="Adder">
  <port name="AdderPort" binding="tns:AdderPort">
   <soap:address location="http://localhost:7001/myServiceApp/Adder">
   </soap:address>
  </port>
 </service>
</definitions>